package Project_Euler;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

public class Even_Fibonacci_Numbers {

    public static void main(String[] args) {
        int sum = 0;
        int a = 0;
        int b = 1;
        int c = a + b;
        // a and b beginning of sequence will reassign them after while loop
        while (c < 4000000){
            //System.out.println(c);
            //print statment shows sequence up to 4 mil
            if (c % 2 == 0){
                //finds out if even
                sum = sum + c;
                //adds them together (assigns to sum inside the loop)
            }
            a = b;
            b = c;
            c = a + b;
            //reassign them so a becomes b and b becomes c
            //so if c = 1, a becomes 1, b becomes 1 then c becomes 2 cos 1 + 1
            //if c = 2, a becomes 1 then b becomes 2 then c becomes 3 cos 2 + 1 etc
        }
        System.out.println(sum);
    }

}
